import { db } from './firebase.js';
import { ref, onValue } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js';
import { $, esc } from './saas.js';
import { loadEcuador, provinceNames, findProvince, findCanton, fillSelect, norm } from './locations.js';
await loadEcuador();fillSelect($('#province'),provinceNames(),'Todas las provincias');fillSelect($('#canton'),[],'Todos los cantones');fillSelect($('#parish'),[],'Todas las parroquias');
$('#province').addEventListener('change',()=>{const p=findProvince($('#province').value);fillSelect($('#canton'),(p?.cantones||[]).map(c=>c.nombre).sort((a,b)=>a.localeCompare(b,'es')),'Todos los cantones');fillSelect($('#parish'),[],'Todas las parroquias');render();});
$('#canton').addEventListener('change',()=>{const c=findCanton($('#province').value,$('#canton').value);fillSelect($('#parish'),(c?.parroquias||[]).slice().sort((a,b)=>a.localeCompare(b,'es')),'Todas las parroquias');render();});
$('#parish').addEventListener('change',render);$('#searchBtn').addEventListener('click',render);
let all={};onValue(ref(db,'tournaments'),s=>{all=s.val()||{};render();});
function render(){const p=norm($('#province').value),c=norm($('#canton').value),pa=norm($('#parish').value);const list=Object.entries(all).filter(([id,t])=>t.status==='active'&&t.paymentStatus==='paid'&&(!p||norm(t.province)===p)&&(!c||norm(t.canton)===c)&&(!pa||norm(t.parish)===pa));$('#count').textContent=`${list.length} torneo${list.length===1?'':'s'}`;$('#tournaments').innerHTML=list.map(([id,t])=>`<article class="directory-card"><div class="directory-logo">${t.logoUrl?`<img src="${esc(t.logoUrl)}" alt="">`:'⚽'}</div><div class="directory-main"><div class="eyebrow">${esc(t.province||'ECUADOR')}</div><h3>${esc(t.name||'Torneo')}</h3><p>${esc([t.canton,t.parish].filter(Boolean).join(' · '))}</p><small>${esc(t.season||'')}</small></div><a class="arrow-btn" href="index.html?t=${encodeURIComponent(t.slug||id)}">Ver torneo →</a></article>`).join('')||'<div class="empty">No encontramos torneos activos en este sector.</div>';}
