import {db,auth} from './firebase.js';
import {ref,get,set,update,query,orderByChild,equalTo} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {esc,uidKey} from './saas.js';
import {startPayment} from './payment.js';
const $=s=>document.querySelector(s);const params=new URLSearchParams(location.search);const tid=params.get('tid');let user=null,tournament=null,settings={};
onAuthStateChanged(auth,async u=>{if(!u){location.href='login.html';return;}user=u;await load();});
async function load(){if(!tid)return show('Falta identificar el torneo.');const [ts,ss]=await Promise.all([get(ref(db,`tournaments/${tid}`)),get(ref(db,'paymentConfig/public'))]);if(!ts.exists())return show('Torneo no encontrado.');tournament=ts.val();settings=ss.val()||{};if(tournament.ownerUid!==user.uid)return show('No tienes permiso sobre este torneo.');if(tournament.paymentStatus==='paid')return renderPaid();render();}
function show(t){$('#paymentMethods').innerHTML=`<div class="empty">${esc(t)}</div>`;}
function renderPaid(){$('#title').textContent='Torneo activado';$('#subtitle').textContent='Este torneo ya tiene el pago confirmado y está publicado.';show('✅ Pago confirmado. Ya puedes administrar tu campeonato.');}
function render(){const tr=settings.transfer||{};const pp=settings.payphone||{};const blocks=[];if(tr.enabled!==false){blocks.push(`<article class="payment-option"><div class="payment-option-head"><div><span class="payment-icon">🏦</span><div><h3>Transferencia bancaria</h3><small>Confirmación manual por el administrador</small></div></div><span class="payment-default">ACTIVA</span></div><div class="bank-details"><div><small>Banco</small><b>${esc(tr.bankName||'No configurado')}</b></div><div><small>Tipo de cuenta</small><b>${esc(tr.accountType||'')}</b></div><div><small>Número de cuenta</small><b>${esc(tr.accountNumber||'')}</b></div><div><small>Titular</small><b>${esc(tr.accountHolder||'')}</b></div><div><small>Cédula / RUC</small><b>${esc(tr.identification||'')}</b></div><div><small>Referencia / contacto</small><b>${esc(tr.contact||'')}</b></div></div><p class="payment-instructions">${esc(tr.instructions||'Realiza la transferencia y registra la referencia para solicitar la activación.')}</p><form id="transferForm" class="transfer-form"><label>Referencia de transferencia<input id="transferRef" required placeholder="Ej. 123456789"></label><label>Observación (opcional)<textarea id="transferNote" rows="3" placeholder="Banco, fecha, comprobante, etc."></textarea></label><button class="primary-btn" type="submit">He realizado la transferencia</button></form></article>`)}if(pp.enabled===true){blocks.push(`<article class="payment-option"><div class="payment-option-head"><div><span class="payment-icon">💳</span><div><h3>Pago con tarjeta</h3><small>Pago en línea con Payphone</small></div></div><span class="payment-default online">EN LÍNEA</span></div><p class="payment-instructions">Paga los $20 en línea. El torneo se activará cuando Payphone confirme la transacción.</p><button id="payphoneBtn" class="primary-btn">Pagar $20 con tarjeta</button></article>`)}if(!blocks.length)blocks.push('<div class="empty">No hay métodos de pago habilitados actualmente.</div>');$('#paymentMethods').innerHTML=blocks.join('');$('#transferForm')?.addEventListener('submit',submitTransfer);$('#payphoneBtn')?.addEventListener('click',payphone);}
async function submitTransfer(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const existing=await get(query(ref(db,'paymentRequests'),orderByChild('uid'),equalTo(user.uid)));const already=Object.values(existing.val()||{}).find(x=>x&&x.tournamentId===tid&&x.status==='pending');if(already)throw new Error('Ya existe una solicitud de transferencia pendiente para este torneo.');const id=uidKey('pago');await set(ref(db,`paymentRequests/${id}`),{id,tournamentId:tid,uid:user.uid,userEmail:user.email||'',method:'transfer',amount:20,currency:'USD',reference:$('#transferRef').value.trim(),note:$('#transferNote').value.trim(),status:'pending',createdAt:Date.now()});await update(ref(db,`tournaments/${tid}`),{paymentStatus:'pending_transfer',paymentProvider:'transfer',paymentRequestId:id});$('#paymentMethods').innerHTML='<div class="success-box">✅ Solicitud enviada.<br><small>Revisaremos la transferencia y activaremos tu torneo cuando el pago sea confirmado.</small><br><a class="primary-btn" href="cuenta.html">Volver a mi cuenta</a></div>';}catch(e){btn.disabled=false;$('#paymentMsg').textContent=e?.message||'No se pudo registrar la transferencia.';}}
async function payphone(e){const btn=e.currentTarget;btn.disabled=true;btn.textContent='Generando pago…';try{await startPayment(tid);btn.textContent='Pago abierto';}catch(err){btn.disabled=false;btn.textContent='Pagar $20 con tarjeta';$('#paymentMsg').textContent=err?.message||'No se pudo iniciar el pago.';}}
